import express from "express";
import path from "path";
import userRouter from "./user.route";
import favouriteRouter from "./favourite.route";
import homeHealthRouter from "./homeHealth.route";
import dmeRouter from "./dme.route";
import referralsRouter from "./referrals.route";
import hospiceRouter from "./hospice.route";
import facultyPreferenceRouter from "./facultyPreference.route";
import woundCareRouter from "./woundCare.route";
const router = express.Router();

router.use("/auth", userRouter);
router.use("/favourites", favouriteRouter);
router.use("/home-health", homeHealthRouter);
router.use("/dme", dmeRouter);
router.use("/referrals", referralsRouter);
router.use("/hospice", hospiceRouter);
router.use("/faculty-preferences", facultyPreferenceRouter);
router.use("/wound-care", woundCareRouter);
export default router;